ESPIDF = /home/ironsst/workspace/esp-idf
PORT = /dev/ttyUSB2
#FLASH_MODE = qio
#FLASH_SIZE = 4MB
CROSS_COMPILE = /opt/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-
SDKCONFIG = boards/sdkconfig.m5stack

include Makefile

