DEV_HOME=/home/stephen/workspace
ESPIDF=$(DEV_HOME)/esp-idf
PORT ?= /dev/ttyUSB0
#FLASH_MODE = qio
#FLASH_SIZE = 4MB
CROSS_COMPILE = $(DEV_HOME)/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-
SDKCONFIG = boards/sdkconfig.m5stack

include Makefile

